export const metadata = {
  title: 'BrixAI Apps',
  description: 'Generated by AI Apps',
}

export default function AiAppsLayout({ children }) {
 return (
      <div>
        {children}
      </div>
  )
}
