export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Dashboard',
}

export default function DashboardLayout({ children }) {
 return (
      <div>
        {children}
      </div>
  )
}
